### PR TITLE
Use Native Brotli

### LINKED ISSUE #4: Support node brotli
See https://github.com/nodejs/node/pull/24938.

### PR DESCRIPTION
**Pull request by salzhrani**
I had to disable coverage for code branches that are always true or false depending on node version

should close #4

### CODE REVIEW

**Review by kanongil — CHANGES_REQUESTED** [review]
Thanks for the PR.

I think I would rather just publish a version 4, that only uses the native code. Or do you have any reason why both should be supported?

**Comment by salzhrani** [comment]
we can make it a major version bump and drop support for node < 10.16.

**Comment by salzhrani** [comment]
updated to use only native brotli

**Review by kanongil — APPROVED** [review]

**Comment by kanongil** [comment]
v4 has been published with some additional fixes. It should work as a drop-in replacement.

**Pull request merged**
